### ISSUE TITLE
Inaccurate installation instructions in the "Contributing" page

### ISSUE THREAD

**Issue by deansg** [Goldziher/go-utils#42]
Step 2 Contributing.md guide specifies how to install relevant pre-commit hooks. However, it seems to me like there is a problem with the linked command, as the pre-commit command line doesn't have a command `pre-commit install-hooksgit`. I assume the intention was to navigate to the project folder and run `pre-commint install-hooks`. If that is the case, it'd be better if the command is fixed, and if the need to navigate to the project dir is specifically listed.

**Comment by Goldziher** [comment]
I don't completely understand your issue. Would you like to submit a fix?

**Comment by deansg** [comment]
In this file:
https://github.com/Goldziher/go-utils/blob/main/CONTRIBUTING.md

Step 2 says:

> Install [pre-commit](https://pre-commit.com/) and install the hook by running:
> pre-commit install \
>    && pre-commit install --hook-type commit-msg \
>    && pre-commit install-hooksgit

I believe there's a mistake in the command given, since there's no such command as `pre-commit install-hooksgit`. I don't mind submitting a fix I'm just not 100% sure what was intended instead.
